@startuml
' diagramme de séquences systeme pour use case "créer client"

actor Chef_De_Projet

Chef_De_Projet -> systeme : créer client

activate systeme

Chef_De_Projet -> systeme : envoie de l'id du client
Chef_De_Projet -> systeme : nom du client
Chef_De_Projet -> systeme : entreprise client
Chef_De_Projet -> systeme : email client
Chef_De_Projet -> systeme : telephone client
Chef_De_Projet -> systeme : envoie de l'id du projet associé au client 

systeme -> systeme : vérification validité des champs

alt vérifie les conditions de validité
systeme --> Chef_De_Projet : Client créé
||10||
else ne vérifie pas les condition de validité 
systeme --> Chef_De_Projet : Champs invalide
end

@enduml